---
- name: Instalar servidor web
  hosts: all
  become: yes
  tasks:
  - name: Software Install
    yum:
      name: httpd
      state: latest
  - name: Active service
    service:
      name: httpd
      enabled: true
      state: started
